### ISSUE TITLE
[FEAT] Add Rate Limiter to the backend of mern Stack project

### ISSUE THREAD

**Issue by Prasundas99** [Prasundas99/Web-Development-Traning#130]
**Is your feature request related to a problem? Please describe.**
For better Practice having a rate limiter to backend server is good

**Describe the solution you'd like**
Package Can be used: https://www.npmjs.com/package/express-rate-limit

**Comment by ryan-byte** [comment]
I'll be working on this feature.

**Comment by ryan-byte** [comment]
Done  #185
**Tested the Rate Limiter with this nodejs code after starting the server:**
```
const axios = require("axios");

let requestNum = 0;
const requestURL = "http://localhost:5000/users";


setInterval(async () => {
    try {
        const response = await axios.get(requestURL);
        if (response.status >= 200 && response.status < 300) {
            console.log(`\x1b[32mSuccess: ${requestNum} request made \x1b[0m`);
            requestNum++;
        }
    } catch (error) {
        console.log(`\x1b[31mError: status code ${error.response.status} \x1b[0m`);
    }
}, 100)
```
**output:**

![Capture](https://user-images.githubusercontent.com/52682606/209753576-9a8f1def-f67e-46a5-9b7d-120cc87b2657.PNG)
